// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coffee.proto

package com.test.coffee;

public interface ProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coffee.ProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Страна происхождения зерна
   * </pre>
   *
   * <code>string country = 1;</code>
   * @return The country.
   */
  String getCountry();
  /**
   * <pre>
   * Страна происхождения зерна
   * </pre>
   *
   * <code>string country = 1;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <pre>
   * Сорт зерна
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  String getType();
  /**
   * <pre>
   * Сорт зерна
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <pre>
   * Вес до обжарки (кг)
   * </pre>
   *
   * <code>float weightIn = 3;</code>
   * @return The weightIn.
   */
  float getWeightIn();

  /**
   * <pre>
   * Вес после обжарки (кг)
   * </pre>
   *
   * <code>float weightOut = 4;</code>
   * @return The weightOut.
   */
  float getWeightOut();

  /**
   * <pre>
   * Номер бригады
   * </pre>
   *
   * <code>int32 team = 5;</code>
   * @return The team.
   */
  int getTeam();

  /**
   * <pre>
   * Номер бригады
   * </pre>
   *
   * <code>int32 bagNumber = 6;</code>
   * @return The bagNumber.
   */
  int getBagNumber();
}
