// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coffee.proto

package com.test.coffee;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coffee_ProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coffee_ProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coffee_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coffee_ProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014coffee.proto\022\006coffee\"u\n\016ProductRequest" +
      "\022\017\n\007country\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\020\n\010weigh" +
      "tIn\030\003 \001(\002\022\021\n\tweightOut\030\004 \001(\002\022\014\n\004team\030\005 \001" +
      "(\005\022\021\n\tbagNumber\030\006 \001(\005\"\"\n\017ProductResponse" +
      "\022\017\n\007message\030\001 \001(\t2O\n\016ProductService\022=\n\nP" +
      "roduction\022\026.coffee.ProductRequest\032\027.coff" +
      "ee.ProductResponseB!\n\017com.test.coffeeB\014P" +
      "roductProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_coffee_ProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coffee_ProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coffee_ProductRequest_descriptor,
        new String[] { "Country", "Type", "WeightIn", "WeightOut", "Team", "BagNumber", });
    internal_static_coffee_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_coffee_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coffee_ProductResponse_descriptor,
        new String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
