// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coffee.proto

package com.test.coffee;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coffee.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Сообщение о результате
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <pre>
   * Сообщение о результате
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
