// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coffee.proto

package com.test.coffee;

/**
 * Protobuf type {@code coffee.ProductRequest}
 */
public final class ProductRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coffee.ProductRequest)
    ProductRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductRequest.newBuilder() to construct.
  private ProductRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductRequest() {
    country_ = "";
    type_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            country_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 29: {

            weightIn_ = input.readFloat();
            break;
          }
          case 37: {

            weightOut_ = input.readFloat();
            break;
          }
          case 40: {

            team_ = input.readInt32();
            break;
          }
          case 48: {

            bagNumber_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ProductProto.internal_static_coffee_ProductRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ProductProto.internal_static_coffee_ProductRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ProductRequest.class, Builder.class);
  }

  public static final int COUNTRY_FIELD_NUMBER = 1;
  private volatile Object country_;
  /**
   * <pre>
   * Страна происхождения зерна
   * </pre>
   *
   * <code>string country = 1;</code>
   * @return The country.
   */
  @Override
  public String getCountry() {
    Object ref = country_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      country_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Страна происхождения зерна
   * </pre>
   *
   * <code>string country = 1;</code>
   * @return The bytes for country.
   */
  @Override
  public com.google.protobuf.ByteString
      getCountryBytes() {
    Object ref = country_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      country_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  private volatile Object type_;
  /**
   * <pre>
   * Сорт зерна
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  @Override
  public String getType() {
    Object ref = type_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Сорт зерна
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  @Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    Object ref = type_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEIGHTIN_FIELD_NUMBER = 3;
  private float weightIn_;
  /**
   * <pre>
   * Вес до обжарки (кг)
   * </pre>
   *
   * <code>float weightIn = 3;</code>
   * @return The weightIn.
   */
  @Override
  public float getWeightIn() {
    return weightIn_;
  }

  public static final int WEIGHTOUT_FIELD_NUMBER = 4;
  private float weightOut_;
  /**
   * <pre>
   * Вес после обжарки (кг)
   * </pre>
   *
   * <code>float weightOut = 4;</code>
   * @return The weightOut.
   */
  @Override
  public float getWeightOut() {
    return weightOut_;
  }

  public static final int TEAM_FIELD_NUMBER = 5;
  private int team_;
  /**
   * <pre>
   * Номер бригады
   * </pre>
   *
   * <code>int32 team = 5;</code>
   * @return The team.
   */
  @Override
  public int getTeam() {
    return team_;
  }

  public static final int BAGNUMBER_FIELD_NUMBER = 6;
  private int bagNumber_;
  /**
   * <pre>
   * Номер бригады
   * </pre>
   *
   * <code>int32 bagNumber = 6;</code>
   * @return The bagNumber.
   */
  @Override
  public int getBagNumber() {
    return bagNumber_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(country_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, country_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
    }
    if (Float.floatToRawIntBits(weightIn_) != 0) {
      output.writeFloat(3, weightIn_);
    }
    if (Float.floatToRawIntBits(weightOut_) != 0) {
      output.writeFloat(4, weightOut_);
    }
    if (team_ != 0) {
      output.writeInt32(5, team_);
    }
    if (bagNumber_ != 0) {
      output.writeInt32(6, bagNumber_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(country_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, country_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
    }
    if (Float.floatToRawIntBits(weightIn_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, weightIn_);
    }
    if (Float.floatToRawIntBits(weightOut_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(4, weightOut_);
    }
    if (team_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, team_);
    }
    if (bagNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, bagNumber_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ProductRequest)) {
      return super.equals(obj);
    }
    ProductRequest other = (ProductRequest) obj;

    if (!getCountry()
        .equals(other.getCountry())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (Float.floatToIntBits(getWeightIn())
        != Float.floatToIntBits(
            other.getWeightIn())) return false;
    if (Float.floatToIntBits(getWeightOut())
        != Float.floatToIntBits(
            other.getWeightOut())) return false;
    if (getTeam()
        != other.getTeam()) return false;
    if (getBagNumber()
        != other.getBagNumber()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
    hash = (53 * hash) + getCountry().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + WEIGHTIN_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getWeightIn());
    hash = (37 * hash) + WEIGHTOUT_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getWeightOut());
    hash = (37 * hash) + TEAM_FIELD_NUMBER;
    hash = (53 * hash) + getTeam();
    hash = (37 * hash) + BAGNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getBagNumber();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ProductRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProductRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProductRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProductRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProductRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ProductRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ProductRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProductRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProductRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ProductRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ProductRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ProductRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ProductRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code coffee.ProductRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coffee.ProductRequest)
      ProductRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProductProto.internal_static_coffee_ProductRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProductProto.internal_static_coffee_ProductRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProductRequest.class, Builder.class);
    }

    // Construct using com.test.coffee.ProductRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      country_ = "";

      type_ = "";

      weightIn_ = 0F;

      weightOut_ = 0F;

      team_ = 0;

      bagNumber_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ProductProto.internal_static_coffee_ProductRequest_descriptor;
    }

    @Override
    public ProductRequest getDefaultInstanceForType() {
      return ProductRequest.getDefaultInstance();
    }

    @Override
    public ProductRequest build() {
      ProductRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public ProductRequest buildPartial() {
      ProductRequest result = new ProductRequest(this);
      result.country_ = country_;
      result.type_ = type_;
      result.weightIn_ = weightIn_;
      result.weightOut_ = weightOut_;
      result.team_ = team_;
      result.bagNumber_ = bagNumber_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ProductRequest) {
        return mergeFrom((ProductRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ProductRequest other) {
      if (other == ProductRequest.getDefaultInstance()) return this;
      if (!other.getCountry().isEmpty()) {
        country_ = other.country_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.getWeightIn() != 0F) {
        setWeightIn(other.getWeightIn());
      }
      if (other.getWeightOut() != 0F) {
        setWeightOut(other.getWeightOut());
      }
      if (other.getTeam() != 0) {
        setTeam(other.getTeam());
      }
      if (other.getBagNumber() != 0) {
        setBagNumber(other.getBagNumber());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ProductRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ProductRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object country_ = "";
    /**
     * <pre>
     * Страна происхождения зерна
     * </pre>
     *
     * <code>string country = 1;</code>
     * @return The country.
     */
    public String getCountry() {
      Object ref = country_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        country_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Страна происхождения зерна
     * </pre>
     *
     * <code>string country = 1;</code>
     * @return The bytes for country.
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      Object ref = country_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Страна происхождения зерна
     * </pre>
     *
     * <code>string country = 1;</code>
     * @param value The country to set.
     * @return This builder for chaining.
     */
    public Builder setCountry(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      country_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Страна происхождения зерна
     * </pre>
     *
     * <code>string country = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountry() {
      
      country_ = getDefaultInstance().getCountry();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Страна происхождения зерна
     * </pre>
     *
     * <code>string country = 1;</code>
     * @param value The bytes for country to set.
     * @return This builder for chaining.
     */
    public Builder setCountryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      country_ = value;
      onChanged();
      return this;
    }

    private Object type_ = "";
    /**
     * <pre>
     * Сорт зерна
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The type.
     */
    public String getType() {
      Object ref = type_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * Сорт зерна
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Сорт зерна
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сорт зерна
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сорт зерна
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private float weightIn_ ;
    /**
     * <pre>
     * Вес до обжарки (кг)
     * </pre>
     *
     * <code>float weightIn = 3;</code>
     * @return The weightIn.
     */
    @Override
    public float getWeightIn() {
      return weightIn_;
    }
    /**
     * <pre>
     * Вес до обжарки (кг)
     * </pre>
     *
     * <code>float weightIn = 3;</code>
     * @param value The weightIn to set.
     * @return This builder for chaining.
     */
    public Builder setWeightIn(float value) {
      
      weightIn_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Вес до обжарки (кг)
     * </pre>
     *
     * <code>float weightIn = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeightIn() {
      
      weightIn_ = 0F;
      onChanged();
      return this;
    }

    private float weightOut_ ;
    /**
     * <pre>
     * Вес после обжарки (кг)
     * </pre>
     *
     * <code>float weightOut = 4;</code>
     * @return The weightOut.
     */
    @Override
    public float getWeightOut() {
      return weightOut_;
    }
    /**
     * <pre>
     * Вес после обжарки (кг)
     * </pre>
     *
     * <code>float weightOut = 4;</code>
     * @param value The weightOut to set.
     * @return This builder for chaining.
     */
    public Builder setWeightOut(float value) {
      
      weightOut_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Вес после обжарки (кг)
     * </pre>
     *
     * <code>float weightOut = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeightOut() {
      
      weightOut_ = 0F;
      onChanged();
      return this;
    }

    private int team_ ;
    /**
     * <pre>
     * Номер бригады
     * </pre>
     *
     * <code>int32 team = 5;</code>
     * @return The team.
     */
    @Override
    public int getTeam() {
      return team_;
    }
    /**
     * <pre>
     * Номер бригады
     * </pre>
     *
     * <code>int32 team = 5;</code>
     * @param value The team to set.
     * @return This builder for chaining.
     */
    public Builder setTeam(int value) {
      
      team_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер бригады
     * </pre>
     *
     * <code>int32 team = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTeam() {
      
      team_ = 0;
      onChanged();
      return this;
    }

    private int bagNumber_ ;
    /**
     * <pre>
     * Номер бригады
     * </pre>
     *
     * <code>int32 bagNumber = 6;</code>
     * @return The bagNumber.
     */
    @Override
    public int getBagNumber() {
      return bagNumber_;
    }
    /**
     * <pre>
     * Номер бригады
     * </pre>
     *
     * <code>int32 bagNumber = 6;</code>
     * @param value The bagNumber to set.
     * @return This builder for chaining.
     */
    public Builder setBagNumber(int value) {
      
      bagNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Номер бригады
     * </pre>
     *
     * <code>int32 bagNumber = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearBagNumber() {
      
      bagNumber_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coffee.ProductRequest)
  }

  // @@protoc_insertion_point(class_scope:coffee.ProductRequest)
  private static final ProductRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ProductRequest();
  }

  public static ProductRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductRequest>
      PARSER = new com.google.protobuf.AbstractParser<ProductRequest>() {
    @Override
    public ProductRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<ProductRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public ProductRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

